Vagrant.configure("2") do |config|
  config.vm.define "worker" do |worker|
    worker.vm.box = "ubuntu/focal64"
    worker.vm.hostname = "worker-vm"
    worker.vm.network "private_network", ip: "192.168.56.10"
    worker.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
    worker.vm.provision "shell", inline: <<-SHELL
      cat /vagrant/cloud_init.cfg > /var/lib/cloud/seed/nocloud-net/user-data
      cloud-init clean
      cloud-init init
      cloud-init modules -m final
    SHELL
  end

  config.vm.define "db" do |db|
    db.vm.box = "ubuntu/focal64"
    db.vm.hostname = "db-vm"
    db.vm.network "private_network", ip: "192.168.56.11"
    db.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
    db.vm.provision "shell", inline: <<-SHELL
      cat /vagrant/cloud_init.cfg > /var/lib/cloud/seed/nocloud-net/user-data
      cloud-init clean
      cloud-init init
      cloud-init modules -m final
    SHELL
  end
end