Vagrant.configure("2") do |config|
  config.vm.define "worker" do |worker|
    worker.vm.box = "ubuntu/focal64"
    worker.vm.hostname = "worker-vm"
    worker.vm.network "private_network", ip: "192.168.56.10"
    worker.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
    worker.vm.provision "shell", inline: <<-SHELL
      id -u ansible &>/dev/null || useradd -m -s /bin/bash -G sudo ansible
      echo "ansible ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/ansible
      mkdir -p /home/ansible/.ssh
      echo "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHfKgDEt05h0qYe56FU4UyJmj5qW30GPVju+n/40B/pk zol@DESKTOP-UKS1HHC" > /home/ansible/.ssh/authorized_keys
      chown -R ansible:ansible /home/ansible/.ssh
      chmod 700 /home/ansible/.ssh
      chmod 600 /home/ansible/.ssh/authorized_keys
    SHELL
  end

  config.vm.define "db" do |db|
    db.vm.box = "ubuntu/focal64"
    db.vm.hostname = "db-vm"
    db.vm.network "private_network", ip: "192.168.56.11"
    db.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
    db.vm.provision "shell", inline: <<-SHELL
      id -u ansible &>/dev/null || useradd -m -s /bin/bash -G sudo ansible
      echo "ansible ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/ansible
      mkdir -p /home/ansible/.ssh
      echo "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHfKgDEt05h0qYe56FU4UyJmj5qW30GPVju+n/40B/pk zol@DESKTOP-UKS1HHC" > /home/ansible/.ssh/authorized_keys
      chown -R ansible:ansible /home/ansible/.ssh
      chmod 700 /home/ansible/.ssh
      chmod 600 /home/ansible/.ssh/authorized_keys
    SHELL
  end
end