---
- name: Встановлення Nginx
  apt:
    name: nginx
    state: present

- name: Видалення дефолтного сайту
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: reload nginx

- name: Шаблонізація конфігу Nginx
  template:
    src: myapp.conf.j2
    dest: /etc/nginx/sites-available/myapp
  notify: reload nginx

- name: Активація конфігу myapp
  file:
    src: /etc/nginx/sites-available/myapp
    dest: /etc/nginx/sites-enabled/myapp
    state: link
  notify: reload nginx

- name: Запуск Nginx
  service:
    name: nginx
    state: started
    enabled: yes