---
- name: Базові налаштування (Teacher та Gradebook)
  hosts: all
  become: yes
  roles:
    - base

- name: Налаштування серверів баз даних (MariaDB)
  hosts: db
  become: yes
  roles:
    - mariadb

- name: Налаштування веб-серверів
  hosts: workers
  become: yes
  roles:
    - app_env
    - webapp
    - nginx